#include <list>
using std::list;
#include <algorithm>
using std::advance;

#include "color.h"

class Palette
{
private:
    list<Color> palette;
public:
    Palette() 
    {
        // palette.push_back(Color("#FFE0EB"));
        // palette.push_back(Color("#FFDEED"));
        // palette.push_back(Color("#FFDBF0"));
        // palette.push_back(Color("#FFD9F2"));
        // palette.push_back(Color("#FFD6F5"));
        // palette.push_back(Color("#FFD4F7"));
        // palette.push_back(Color("#FFD1FA"));
        // palette.push_back(Color("#FFCFFC"));
        // palette.push_back(Color("#FFCCFF"));
        // palette.push_back(Color("#FFC7D1"));
        // palette.push_back(Color("#FFC2D6"));
        // palette.push_back(Color("#FFBDDB"));
        // palette.push_back(Color("#FFB8E0"));
        // palette.push_back(Color("#FFB3E6"));
        // palette.push_back(Color("#FFADEB"));
        // palette.push_back(Color("#FFA8F0"));
        // palette.push_back(Color("#FFA3F5"));
        // palette.push_back(Color("#FF9EFA"));
        // palette.push_back(Color("#FF99FF"));
        // palette.push_back(Color("#FFABBA"));
        // palette.push_back(Color("#FFA3C2"));
        // palette.push_back(Color("#FF9CC9"));
        // palette.push_back(Color("#FF94D1"));
        // palette.push_back(Color("#FF8CD9"));
        // palette.push_back(Color("#FF85E0"));
        // palette.push_back(Color("#FF7DE8"));
        // palette.push_back(Color("#FF75F0"));
        // palette.push_back(Color("#FF6EF7"));
        // palette.push_back(Color("#FF66FF"));
        // palette.push_back(Color("#FF8FA3"));
        // palette.push_back(Color("#FF85AD"));
        // palette.push_back(Color("#FF7AB8"));
        // palette.push_back(Color("#FF70C2"));
        // palette.push_back(Color("#FF66CC"));
        // palette.push_back(Color("#FF5CD6"));
        // palette.push_back(Color("#FF52E0"));
        // palette.push_back(Color("#FF47EB"));
        // palette.push_back(Color("#FF3DF5"));
        // palette.push_back(Color("#FF33FF"));
        // palette.push_back(Color("#FF738C"));
        // palette.push_back(Color("#FF6699"));
        // palette.push_back(Color("#FF59A6"));
        // palette.push_back(Color("#FF4DB2"));
        // palette.push_back(Color("#FF40BF"));
        // palette.push_back(Color("#FF33CC"));
        // palette.push_back(Color("#FF26D9"));
        // palette.push_back(Color("#FF19E5"));
        // palette.push_back(Color("#FF0DF2"));
        // palette.push_back(Color("#FF00FF"));
        // palette.push_back(Color("#FF5C70"));
        // palette.push_back(Color("#FF527A"));
        // palette.push_back(Color("#FF4785"));
        // palette.push_back(Color("#FF3D8F"));
        // palette.push_back(Color("#FF3399"));
        // palette.push_back(Color("#FF29A3"));
        // palette.push_back(Color("#FF1FAD"));
        // palette.push_back(Color("#FF14B8"));
        // palette.push_back(Color("#FF0AC2"));
        // palette.push_back(Color("#FF00CC"));
        // palette.push_back(Color("#FF4554"));
        // palette.push_back(Color("#FF3D5C"));
        // palette.push_back(Color("#FF3663"));
        // palette.push_back(Color("#FF2E6B"));
        // palette.push_back(Color("#FF2673"));
        // palette.push_back(Color("#FF1F7A"));
        // palette.push_back(Color("#FF1782"));
        // palette.push_back(Color("#FF0F8A"));
        // palette.push_back(Color("#FF0891"));
        // palette.push_back(Color("#FF0099"));
        // palette.push_back(Color("#FF2E38"));
        // palette.push_back(Color("#FF293D"));
        // palette.push_back(Color("#FF2442"));
        // palette.push_back(Color("#FF1F47"));
        // palette.push_back(Color("#FF194C"));
        // palette.push_back(Color("#FF1452"));
        // palette.push_back(Color("#FF0F57"));
        // palette.push_back(Color("#FF0A5C"));
        // palette.push_back(Color("#FF0561"));
        // palette.push_back(Color("#FF0066"));
        // palette.push_back(Color("#FFE3E8"));
        // palette.push_back(Color("#FFE0EA"));
        // palette.push_back(Color("#FFDEEC"));
        // palette.push_back(Color("#FFDBEE"));
        // palette.push_back(Color("#FFD9F0"));
        // palette.push_back(Color("#FFD6F2"));
        // palette.push_back(Color("#FFD4F4"));
        // palette.push_back(Color("#FFD1F6"));
        // palette.push_back(Color("#FFCFF8"));
        // palette.push_back(Color("#FFCCFA"));
        // palette.push_back(Color("#FFC7D0"));
        // palette.push_back(Color("#FFC2D4"));
        // palette.push_back(Color("#FFBDD8"));
        // palette.push_back(Color("#FFB8DC"));
        // palette.push_back(Color("#FFB3E0"));
        // palette.push_back(Color("#FFADE4"));
        // palette.push_back(Color("#FFA8E9"));
        // palette.push_back(Color("#FFA3ED"));
        // palette.push_back(Color("#FF9EF1"));
        // palette.push_back(Color("#FF99F5"));
        // palette.push_back(Color("#FFABB9"));
        // palette.push_back(Color("#FFA3BF"));
        // palette.push_back(Color("#FF9CC5"));
        // palette.push_back(Color("#FF94CB"));
        // palette.push_back(Color("#FF8CD1"));
        // palette.push_back(Color("#FF85D7"));
        // palette.push_back(Color("#FF7DDD"));
        // palette.push_back(Color("#FF75E3"));
        // palette.push_back(Color("#FF6EEA"));
        // palette.push_back(Color("#FF66F0"));
        // palette.push_back(Color("#FF8FA1"));
        // palette.push_back(Color("#FF85A9"));
        // palette.push_back(Color("#FF7AB1"));
        // palette.push_back(Color("#FF70BA"));
        // palette.push_back(Color("#FF66C2"));
        // palette.push_back(Color("#FF5CCA"));
        // palette.push_back(Color("#FF52D2"));
        // palette.push_back(Color("#FF47DA"));
        // palette.push_back(Color("#FF3DE2"));
        // palette.push_back(Color("#FF33EB"));
        // palette.push_back(Color("#FF738A"));
        // palette.push_back(Color("#FF6694"));
        // palette.push_back(Color("#FF599E"));
        // palette.push_back(Color("#FF4DA8"));
        // palette.push_back(Color("#FF40B2"));
        // palette.push_back(Color("#FF33BD"));
        // palette.push_back(Color("#FF26C7"));
        // palette.push_back(Color("#FF19D1"));
        // palette.push_back(Color("#FF0DDB"));
        // palette.push_back(Color("#FF00E5"));
        // palette.push_back(Color("#FF5C6E"));
        // palette.push_back(Color("#FF5276"));
        // palette.push_back(Color("#FF477E"));
        // palette.push_back(Color("#FF3D87"));
        // palette.push_back(Color("#FF338F"));
        // palette.push_back(Color("#FF2997"));
        // palette.push_back(Color("#FF1F9F"));
        // palette.push_back(Color("#FF14A7"));
        // palette.push_back(Color("#FF0AAF"));
        // palette.push_back(Color("#FF00B8"));
        // palette.push_back(Color("#FF4553"));
        // palette.push_back(Color("#FF3D59"));
        // palette.push_back(Color("#FF365F"));
        // palette.push_back(Color("#FF2E65"));
        // palette.push_back(Color("#FF266B"));
        // palette.push_back(Color("#FF1F71"));
        // palette.push_back(Color("#FF1777"));
        // palette.push_back(Color("#FF0F7D"));
        // palette.push_back(Color("#FF0884"));
        // palette.push_back(Color("#FF008A"));
        // palette.push_back(Color("#FF2E37"));
        // palette.push_back(Color("#FF293B"));
        // palette.push_back(Color("#FF243F"));
        // palette.push_back(Color("#FF1F43"));
        // palette.push_back(Color("#FF1947"));
        // palette.push_back(Color("#FF144B"));
        // palette.push_back(Color("#FF0F50"));
        // palette.push_back(Color("#FF0A54"));
        // palette.push_back(Color("#FF0558"));
        // palette.push_back(Color("#FF005C"));
        // palette.push_back(Color("#FFE3E7"));
        // palette.push_back(Color("#FFE0E9"));
        // palette.push_back(Color("#FFDEEA"));
        // palette.push_back(Color("#FFDBEC"));
        // palette.push_back(Color("#FFD9ED"));
        // palette.push_back(Color("#FFD6EF"));
        // palette.push_back(Color("#FFD4F0"));
        // palette.push_back(Color("#FFD1F2"));
        // palette.push_back(Color("#FFCFF3"));
        // palette.push_back(Color("#FFCCF5"));
        // palette.push_back(Color("#FFC7CF"));
        // palette.push_back(Color("#FFC2D2"));
        // palette.push_back(Color("#FFBDD5"));
        // palette.push_back(Color("#FFB8D8"));
        // palette.push_back(Color("#FFB3DB"));
        // palette.push_back(Color("#FFADDE"));
        // palette.push_back(Color("#FFA8E1"));
        // palette.push_back(Color("#FFA3E4"));
        // palette.push_back(Color("#FF9EE8"));
        // palette.push_back(Color("#FF99EB"));
        // palette.push_back(Color("#FFABB7"));
        // palette.push_back(Color("#FFA3BC"));
        // palette.push_back(Color("#FF9CC0"));
        // palette.push_back(Color("#FF94C5"));
        // palette.push_back(Color("#FF8CC9"));
        // palette.push_back(Color("#FF85CE"));
        // palette.push_back(Color("#FF7DD3"));
        // palette.push_back(Color("#FF75D7"));
        // palette.push_back(Color("#FF6EDC"));
        // palette.push_back(Color("#FF66E0"));
        // palette.push_back(Color("#FF8F9F"));
        // palette.push_back(Color("#FF85A5"));
        // palette.push_back(Color("#FF7AAB"));
        // palette.push_back(Color("#FF70B1"));
        // palette.push_back(Color("#FF66B8"));
        // palette.push_back(Color("#FF5CBE"));
        // palette.push_back(Color("#FF52C4"));
        // palette.push_back(Color("#FF47CA"));
        // palette.push_back(Color("#FF3DD0"));
        // palette.push_back(Color("#FF33D6"));
        // palette.push_back(Color("#FF7387"));
        // palette.push_back(Color("#FF668F"));
        // palette.push_back(Color("#FF5996"));
        // palette.push_back(Color("#FF4D9E"));
        // palette.push_back(Color("#FF40A6"));
        // palette.push_back(Color("#FF33AD"));
        // palette.push_back(Color("#FF26B5"));
        // palette.push_back(Color("#FF19BD"));
        // palette.push_back(Color("#FF0DC4"));
        // palette.push_back(Color("#FF00CC"));
        // palette.push_back(Color("#FF5C6C"));
        // palette.push_back(Color("#FF5272"));
        // palette.push_back(Color("#FF4778"));
        // palette.push_back(Color("#FF3D7E"));
        // palette.push_back(Color("#FF3385"));
        // palette.push_back(Color("#FF298B"));
        // palette.push_back(Color("#FF1F91"));
        // palette.push_back(Color("#FF1497"));
        // palette.push_back(Color("#FF0A9D"));
        // palette.push_back(Color("#FF00A3"));
        // palette.push_back(Color("#FF4551"));
        // palette.push_back(Color("#FF3D56"));
        // palette.push_back(Color("#FF365A"));
        // palette.push_back(Color("#FF2E5F"));
        // palette.push_back(Color("#FF2663"));
        // palette.push_back(Color("#FF1F68"));
        // palette.push_back(Color("#FF176D"));
        // palette.push_back(Color("#FF0F71"));
        // palette.push_back(Color("#FF0876"));
        // palette.push_back(Color("#FF007A"));
        // palette.push_back(Color("#FF2E36"));
        // palette.push_back(Color("#FF2939"));
        // palette.push_back(Color("#FF243C"));
        // palette.push_back(Color("#FF1F3F"));
        // palette.push_back(Color("#FF1942"));
        // palette.push_back(Color("#FF1445"));
        // palette.push_back(Color("#FF0F48"));
        // palette.push_back(Color("#FF0A4B"));
        // palette.push_back(Color("#FF054F"));
        // palette.push_back(Color("#FF0052"));
        // palette.push_back(Color("#FFE3E7"));
        // palette.push_back(Color("#FFE0E8"));
        // palette.push_back(Color("#FFDEE9"));
        // palette.push_back(Color("#FFDBEA"));
        // palette.push_back(Color("#FFD9EB"));
        // palette.push_back(Color("#FFD6EC"));
        // palette.push_back(Color("#FFD4ED"));
        // palette.push_back(Color("#FFD1EE"));
        // palette.push_back(Color("#FFCFEF"));
        // palette.push_back(Color("#FFCCF0"));
        // palette.push_back(Color("#FFC7CE"));
        // palette.push_back(Color("#FFC2D0"));
        // palette.push_back(Color("#FFBDD2"));
        // palette.push_back(Color("#FFB8D4"));
        // palette.push_back(Color("#FFB3D6"));
        // palette.push_back(Color("#FFADD8"));
        // palette.push_back(Color("#FFA8DA"));
        // palette.push_back(Color("#FFA3DC"));
        // palette.push_back(Color("#FF9EDE"));
        // palette.push_back(Color("#FF99E0"));
        // palette.push_back(Color("#FFABB6"));
        // palette.push_back(Color("#FFA3B9"));
        // palette.push_back(Color("#FF9CBC"));
        // palette.push_back(Color("#FF94BF"));
        // palette.push_back(Color("#FF8CC2"));
        // palette.push_back(Color("#FF85C5"));
        // palette.push_back(Color("#FF7DC8"));
        // palette.push_back(Color("#FF75CB"));
        // palette.push_back(Color("#FF6ECE"));
        // palette.push_back(Color("#FF66D1"));
        // palette.push_back(Color("#FF8F9D"));
        // palette.push_back(Color("#FF85A1"));
        // palette.push_back(Color("#FF7AA5"));
        // palette.push_back(Color("#FF70A9"));
        // palette.push_back(Color("#FF66AD"));
        // palette.push_back(Color("#FF5CB1"));
        // palette.push_back(Color("#FF52B6"));
        // palette.push_back(Color("#FF47BA"));
        // palette.push_back(Color("#FF3DBE"));
        // palette.push_back(Color("#FF33C2"));
        // palette.push_back(Color("#FF7385"));
        // palette.push_back(Color("#FF668A"));
        // palette.push_back(Color("#FF598F"));
        // palette.push_back(Color("#FF4D94"));
        // palette.push_back(Color("#FF4099"));
        // palette.push_back(Color("#FF339E"));
        // palette.push_back(Color("#FF26A3"));
        // palette.push_back(Color("#FF19A8"));
        // palette.push_back(Color("#FF0DAD"));
        // palette.push_back(Color("#FF00B2"));
        // palette.push_back(Color("#FF5C6A"));
        // palette.push_back(Color("#FF526E"));
        // palette.push_back(Color("#FF4772"));
        // palette.push_back(Color("#FF3D76"));
        // palette.push_back(Color("#FF337A"));
        // palette.push_back(Color("#FF297E"));
        // palette.push_back(Color("#FF1F83"));
        // palette.push_back(Color("#FF1487"));
        // palette.push_back(Color("#FF0A8B"));
        // palette.push_back(Color("#FF008F"));
        // palette.push_back(Color("#FF4550"));
        // palette.push_back(Color("#FF3D53"));
        // palette.push_back(Color("#FF3656"));
        // palette.push_back(Color("#FF2E59"));
        // palette.push_back(Color("#FF265C"));
        // palette.push_back(Color("#FF1F5F"));
        // palette.push_back(Color("#FF1762"));
        // palette.push_back(Color("#FF0F65"));
        // palette.push_back(Color("#FF0868"));
        // palette.push_back(Color("#FF006B"));
        // palette.push_back(Color("#FF2E35"));
        // palette.push_back(Color("#FF2937"));
        // palette.push_back(Color("#FF2439"));
        // palette.push_back(Color("#FF1F3B"));
        // palette.push_back(Color("#FF193D"));
        // palette.push_back(Color("#FF143F"));
        // palette.push_back(Color("#FF0F41"));
        // palette.push_back(Color("#FF0A43"));
        // palette.push_back(Color("#FF0545"));
        // palette.push_back(Color("#FF0047"));
        // palette.push_back(Color("#FFE3E6"));
        // palette.push_back(Color("#FFE0E7"));
        // palette.push_back(Color("#FFDEE7"));
        // palette.push_back(Color("#FFDBE8"));
        // palette.push_back(Color("#FFD9E8"));
        // palette.push_back(Color("#FFD6E9"));
        // palette.push_back(Color("#FFD4E9"));
        // palette.push_back(Color("#FFD1EA"));
        // palette.push_back(Color("#FFCFEA"));
        // palette.push_back(Color("#FFCCEB"));
        // palette.push_back(Color("#FFC7CD"));
        // palette.push_back(Color("#FFC2CE"));
        // palette.push_back(Color("#FFBDCF"));
        // palette.push_back(Color("#FFB8D0"));
        // palette.push_back(Color("#FFB3D1"));
        // palette.push_back(Color("#FFADD2"));
        // palette.push_back(Color("#FFA8D3"));
        // palette.push_back(Color("#FFA3D4"));
        // palette.push_back(Color("#FF9ED5"));
        // palette.push_back(Color("#FF99D6"));
        // palette.push_back(Color("#FFABB4"));
        // palette.push_back(Color("#FFA3B6"));
        // palette.push_back(Color("#FF9CB7"));
        // palette.push_back(Color("#FF94B9"));
        // palette.push_back(Color("#FF8CBA"));
        // palette.push_back(Color("#FF85BC"));
        // palette.push_back(Color("#FF7DBD"));
        // palette.push_back(Color("#FF75BF"));
        // palette.push_back(Color("#FF6EC0"));
        // palette.push_back(Color("#FF66C2"));
        // palette.push_back(Color("#FF8F9B"));
        // palette.push_back(Color("#FF859D"));
        // palette.push_back(Color("#FF7A9F"));
        // palette.push_back(Color("#FF70A1"));
        // palette.push_back(Color("#FF66A3"));
        // palette.push_back(Color("#FF5CA5"));
        // palette.push_back(Color("#FF52A7"));
        // palette.push_back(Color("#FF47A9"));
        // palette.push_back(Color("#FF3DAB"));
        // palette.push_back(Color("#FF33AD"));
        // palette.push_back(Color("#FF7382"));
        // palette.push_back(Color("#FF6685"));
        // palette.push_back(Color("#FF5987"));
        // palette.push_back(Color("#FF4D8A"));
        // palette.push_back(Color("#FF408C"));
        // palette.push_back(Color("#FF338F"));
        // palette.push_back(Color("#FF2691"));
        // palette.push_back(Color("#FF1994"));
        // palette.push_back(Color("#FF0D96"));
        // palette.push_back(Color("#FF0099"));
        // palette.push_back(Color("#FF5C68"));
        // palette.push_back(Color("#FF526A"));
        // palette.push_back(Color("#FF476C"));
        // palette.push_back(Color("#FF3D6E"));
        // palette.push_back(Color("#FF3370"));
        // palette.push_back(Color("#FF2972"));
        // palette.push_back(Color("#FF1F74"));
        // palette.push_back(Color("#FF1476"));
        // palette.push_back(Color("#FF0A78"));
        // palette.push_back(Color("#FF007A"));
        // palette.push_back(Color("#FF454E"));
        // palette.push_back(Color("#FF3D50"));
        // palette.push_back(Color("#FF3651"));
        // palette.push_back(Color("#FF2E53"));
        // palette.push_back(Color("#FF2654"));
        // palette.push_back(Color("#FF1F56"));
        // palette.push_back(Color("#FF1757"));
        // palette.push_back(Color("#FF0F59"));
        // palette.push_back(Color("#FF085A"));
        // palette.push_back(Color("#FF005C"));
        // palette.push_back(Color("#FF2E34"));
        // palette.push_back(Color("#FF2935"));
        // palette.push_back(Color("#FF2436"));
        // palette.push_back(Color("#FF1F37"));
        // palette.push_back(Color("#FF1938"));
        // palette.push_back(Color("#FF1439"));
        // palette.push_back(Color("#FF0F3A"));
        // palette.push_back(Color("#FF0A3B"));
        // palette.push_back(Color("#FF053C"));
        // palette.push_back(Color("#FF003D"));
        // palette.push_back(Color("#FFE3E6"));
        // palette.push_back(Color("#FFE0E6"));
        // palette.push_back(Color("#FFDEE6"));
        // palette.push_back(Color("#FFDBE6"));
        // palette.push_back(Color("#FFD9E6"));
        // palette.push_back(Color("#FFD6E6"));
        // palette.push_back(Color("#FFD4E5"));
        // palette.push_back(Color("#FFD1E5"));
        // palette.push_back(Color("#FFCFE5"));
        // palette.push_back(Color("#FFCCE5"));
        // palette.push_back(Color("#FFC7CC"));
        // palette.push_back(Color("#FFC2CC"));
        // palette.push_back(Color("#FFBDCC"));
        // palette.push_back(Color("#FFB8CC"));
        // palette.push_back(Color("#FFB3CC"));
        // palette.push_back(Color("#FFADCC"));
        // palette.push_back(Color("#FFA8CC"));
        // palette.push_back(Color("#FFA3CC"));
        // palette.push_back(Color("#FF9ECC"));
        // palette.push_back(Color("#FF99CC"));
        // palette.push_back(Color("#FFABB2"));
        // palette.push_back(Color("#FFA3B2"));
        // palette.push_back(Color("#FF9CB2"));
        // palette.push_back(Color("#FF94B2"));
        // palette.push_back(Color("#FF8CB2"));
        // palette.push_back(Color("#FF85B2"));
        // palette.push_back(Color("#FF7DB2"));
        // palette.push_back(Color("#FF75B2"));
        // palette.push_back(Color("#FF6EB2"));
        // palette.push_back(Color("#FF66B2"));
        // palette.push_back(Color("#FF8F99"));
        // palette.push_back(Color("#FF8599"));
        // palette.push_back(Color("#FF7A99"));
        // palette.push_back(Color("#FF7099"));
        // palette.push_back(Color("#FF6699"));
        // palette.push_back(Color("#FF5C99"));
        // palette.push_back(Color("#FF5299"));
        // palette.push_back(Color("#FF4799"));
        // palette.push_back(Color("#FF3D99"));
        // palette.push_back(Color("#FF3399"));
        // palette.push_back(Color("#FF737F"));
        // palette.push_back(Color("#FF667F"));
        // palette.push_back(Color("#FF597F"));
        // palette.push_back(Color("#FF4D7F"));
        // palette.push_back(Color("#FF407F"));
        // palette.push_back(Color("#FF337F"));
        // palette.push_back(Color("#FF267F"));
        // palette.push_back(Color("#FF197F"));
        // palette.push_back(Color("#FF0D7F"));
        // palette.push_back(Color("#FF007F"));
        // palette.push_back(Color("#FF5C66"));
        // palette.push_back(Color("#FF5266"));
        // palette.push_back(Color("#FF4766"));
        // palette.push_back(Color("#FF3D66"));
        // palette.push_back(Color("#FF3366"));
        // palette.push_back(Color("#FF2966"));
        // palette.push_back(Color("#FF1F66"));
        // palette.push_back(Color("#FF1466"));
        // palette.push_back(Color("#FF0A66"));
        // palette.push_back(Color("#FF0066"));
        // palette.push_back(Color("#FF454C"));
        // palette.push_back(Color("#FF3D4C"));
        // palette.push_back(Color("#FF364C"));
        // palette.push_back(Color("#FF2E4C"));
        // palette.push_back(Color("#FF264C"));
        // palette.push_back(Color("#FF1F4C"));
        // palette.push_back(Color("#FF174C"));
        // palette.push_back(Color("#FF0F4C"));
        // palette.push_back(Color("#FF084C"));
        // palette.push_back(Color("#FF004C"));
        // palette.push_back(Color("#FF2E33"));
        // palette.push_back(Color("#FF2933"));
        // palette.push_back(Color("#FF2433"));
        // palette.push_back(Color("#FF1F33"));
        // palette.push_back(Color("#FF1933"));
        // palette.push_back(Color("#FF1433"));
        // palette.push_back(Color("#FF0F33"));
        // palette.push_back(Color("#FF0A33"));
        // palette.push_back(Color("#FF0533"));
        // palette.push_back(Color("#FF0033"));
        // palette.push_back(Color("#FFE3E5"));
        // palette.push_back(Color("#FFE0E4"));
        // palette.push_back(Color("#FFDEE4"));
        // palette.push_back(Color("#FFDBE3"));
        // palette.push_back(Color("#FFD9E3"));
        // palette.push_back(Color("#FFD6E2"));
        // palette.push_back(Color("#FFD4E2"));
        // palette.push_back(Color("#FFD1E1"));
        // palette.push_back(Color("#FFCFE1"));
        // palette.push_back(Color("#FFCCE0"));
        // palette.push_back(Color("#FFC7CB"));
        // palette.push_back(Color("#FFC2CA"));
        // palette.push_back(Color("#FFBDC9"));
        // palette.push_back(Color("#FFB8C8"));
        // palette.push_back(Color("#FFB3C7"));
        // palette.push_back(Color("#FFADC6"));
        // palette.push_back(Color("#FFA8C5"));
        // palette.push_back(Color("#FFA3C4"));
        // palette.push_back(Color("#FF9EC3"));
        // palette.push_back(Color("#FF99C2"));
        // palette.push_back(Color("#FFABB1"));
        // palette.push_back(Color("#FFA3AF"));
        // palette.push_back(Color("#FF9CAE"));
        // palette.push_back(Color("#FF94AC"));
        // palette.push_back(Color("#FF8CAB"));
        // palette.push_back(Color("#FF85A9"));
        // palette.push_back(Color("#FF7DA8"));
        // palette.push_back(Color("#FF75A6"));
        // palette.push_back(Color("#FF6EA5"));
        // palette.push_back(Color("#FF66A3"));
        // palette.push_back(Color("#FF8F97"));
        // palette.push_back(Color("#FF8595"));
        // palette.push_back(Color("#FF7A93"));
        // palette.push_back(Color("#FF7091"));
        // palette.push_back(Color("#FF668F"));
        // palette.push_back(Color("#FF5C8D"));
        // palette.push_back(Color("#FF528B"));
        // palette.push_back(Color("#FF4789"));
        // palette.push_back(Color("#FF3D87"));
        // palette.push_back(Color("#FF3385"));
        // palette.push_back(Color("#FF737D"));
        // palette.push_back(Color("#FF667A"));
        // palette.push_back(Color("#FF5978"));
        // palette.push_back(Color("#FF4D75"));
        // palette.push_back(Color("#FF4073"));
        // palette.push_back(Color("#FF3370"));
        // palette.push_back(Color("#FF266E"));
        // palette.push_back(Color("#FF196B"));
        // palette.push_back(Color("#FF0D69"));
        // palette.push_back(Color("#FF0066"));
        // palette.push_back(Color("#FF5C64"));
        // palette.push_back(Color("#FF5262"));
        // palette.push_back(Color("#FF4760"));
        // palette.push_back(Color("#FF3D5E"));
        // palette.push_back(Color("#FF335C"));
        // palette.push_back(Color("#FF295A"));
        // palette.push_back(Color("#FF1F58"));
        // palette.push_back(Color("#FF1456"));
        // palette.push_back(Color("#FF0A54"));
        // palette.push_back(Color("#FF0052"));
        // palette.push_back(Color("#FF454B"));
        // palette.push_back(Color("#FF3D49"));
        // palette.push_back(Color("#FF3648"));
        // palette.push_back(Color("#FF2E46"));
        // palette.push_back(Color("#FF2645"));
        // palette.push_back(Color("#FF1F43"));
        // palette.push_back(Color("#FF1742"));
        // palette.push_back(Color("#FF0F40"));
        // palette.push_back(Color("#FF083F"));
        // palette.push_back(Color("#FF003D"));
        // palette.push_back(Color("#FF2E32"));
        // palette.push_back(Color("#FF2931"));
        // palette.push_back(Color("#FF2430"));
        // palette.push_back(Color("#FF1F2F"));
        // palette.push_back(Color("#FF192E"));
        // palette.push_back(Color("#FF142D"));
        // palette.push_back(Color("#FF0F2C"));
        // palette.push_back(Color("#FF0A2B"));
        // palette.push_back(Color("#FF052A"));
        // palette.push_back(Color("#FF0029"));
        // palette.push_back(Color("#FFE3E4"));
        // palette.push_back(Color("#FFE0E3"));
        // palette.push_back(Color("#FFDEE2"));
        // palette.push_back(Color("#FFDBE1"));
        // palette.push_back(Color("#FFD9E0"));
        // palette.push_back(Color("#FFD6DF"));
        // palette.push_back(Color("#FFD4DE"));
        // palette.push_back(Color("#FFD1DD"));
        // palette.push_back(Color("#FFCFDC"));
        // palette.push_back(Color("#FFCCDB"));
        // palette.push_back(Color("#FFC7CA"));
        // palette.push_back(Color("#FFC2C8"));
        // palette.push_back(Color("#FFBDC6"));
        // palette.push_back(Color("#FFB8C4"));
        // palette.push_back(Color("#FFB3C2"));
        // palette.push_back(Color("#FFADC0"));
        // palette.push_back(Color("#FFA8BE"));
        // palette.push_back(Color("#FFA3BC"));
        // palette.push_back(Color("#FF9EBA"));
        // palette.push_back(Color("#FF99B8"));
        // palette.push_back(Color("#FFABAF"));
        // palette.push_back(Color("#FFA3AC"));
        // palette.push_back(Color("#FF9CA9"));
        // palette.push_back(Color("#FF94A6"));
        // palette.push_back(Color("#FF8CA3"));
        // palette.push_back(Color("#FF85A0"));
        // palette.push_back(Color("#FF7D9D"));
        // palette.push_back(Color("#FF759A"));
        // palette.push_back(Color("#FF6E97"));
        // palette.push_back(Color("#FF6694"));
        // palette.push_back(Color("#FF8F95"));
        // palette.push_back(Color("#FF8591"));
        // palette.push_back(Color("#FF7A8D"));
        // palette.push_back(Color("#FF7089"));
        // palette.push_back(Color("#FF6685"));
        // palette.push_back(Color("#FF5C81"));
        // palette.push_back(Color("#FF527C"));
        // palette.push_back(Color("#FF4778"));
        // palette.push_back(Color("#FF3D74"));
        // palette.push_back(Color("#FF3370"));
        // palette.push_back(Color("#FF737A"));
        // palette.push_back(Color("#FF6675"));
        // palette.push_back(Color("#FF5970"));
        // palette.push_back(Color("#FF4D6B"));
        // palette.push_back(Color("#FF4066"));
        // palette.push_back(Color("#FF3361"));
        // palette.push_back(Color("#FF265C"));
        // palette.push_back(Color("#FF1957"));
        // palette.push_back(Color("#FF0D52"));
        // palette.push_back(Color("#FF004C"));
        // palette.push_back(Color("#FF5C62"));
        // palette.push_back(Color("#FF525E"));
        // palette.push_back(Color("#FF475A"));
        // palette.push_back(Color("#FF3D56"));
        // palette.push_back(Color("#FF3352"));
        // palette.push_back(Color("#FF294E"));
        // palette.push_back(Color("#FF1F49"));
        // palette.push_back(Color("#FF1445"));
        // palette.push_back(Color("#FF0A41"));
        // palette.push_back(Color("#FF003D"));
        // palette.push_back(Color("#FF4549"));
        // palette.push_back(Color("#FF3D46"));
        // palette.push_back(Color("#FF3643"));
        // palette.push_back(Color("#FF2E40"));
        // palette.push_back(Color("#FF263D"));
        // palette.push_back(Color("#FF1F3A"));
        // palette.push_back(Color("#FF1737"));
        // palette.push_back(Color("#FF0F34"));
        // palette.push_back(Color("#FF0831"));
        // palette.push_back(Color("#FF002E"));
        // palette.push_back(Color("#FF2E31"));
        // palette.push_back(Color("#FF292F"));
        // palette.push_back(Color("#FF242D"));
        // palette.push_back(Color("#FF1F2B"));
        // palette.push_back(Color("#FF1929"));
        // palette.push_back(Color("#FF1427"));
        // palette.push_back(Color("#FF0F25"));
        // palette.push_back(Color("#FF0A23"));
        // palette.push_back(Color("#FF0521"));
        // palette.push_back(Color("#FF001F"));
        // palette.push_back(Color("#FFE3E4"));
        // palette.push_back(Color("#FFE0E2"));
        // palette.push_back(Color("#FFDEE1"));
        // palette.push_back(Color("#FFDBDF"));
        // palette.push_back(Color("#FFD9DE"));
        // palette.push_back(Color("#FFD6DC"));
        // palette.push_back(Color("#FFD4DB"));
        // palette.push_back(Color("#FFD1D9"));
        // palette.push_back(Color("#FFCFD8"));
        // palette.push_back(Color("#FFCCD6"));
        // palette.push_back(Color("#FFC7C9"));
        // palette.push_back(Color("#FFC2C6"));
        // palette.push_back(Color("#FFBDC3"));
        // palette.push_back(Color("#FFB8C0"));
        // palette.push_back(Color("#FFB3BD"));
        // palette.push_back(Color("#FFADBA"));
        // palette.push_back(Color("#FFA8B7"));
        // palette.push_back(Color("#FFA3B4"));
        // palette.push_back(Color("#FF9EB0"));
        // palette.push_back(Color("#FF99AD"));
        // palette.push_back(Color("#FFABAE"));
        // palette.push_back(Color("#FFA3A9"));
        // palette.push_back(Color("#FF9CA5"));
        // palette.push_back(Color("#FF94A0"));
        // palette.push_back(Color("#FF8C9C"));
        // palette.push_back(Color("#FF8597"));
        // palette.push_back(Color("#FF7D92"));
        // palette.push_back(Color("#FF758E"));
        // palette.push_back(Color("#FF6E89"));
        // palette.push_back(Color("#FF6685"));
        // palette.push_back(Color("#FF8F93"));
        // palette.push_back(Color("#FF858D"));
        // palette.push_back(Color("#FF7A87"));
        // palette.push_back(Color("#FF7081"));
        // palette.push_back(Color("#FF667A"));
        // palette.push_back(Color("#FF5C74"));
        // palette.push_back(Color("#FF526E"));
        // palette.push_back(Color("#FF4768"));
        // palette.push_back(Color("#FF3D62"));
        // palette.push_back(Color("#FF335C"));
        // palette.push_back(Color("#FF7378"));
        // palette.push_back(Color("#FF6670"));
        // palette.push_back(Color("#FF5969"));
        // palette.push_back(Color("#FF4D61"));
        // palette.push_back(Color("#FF4059"));
        // palette.push_back(Color("#FF3352"));
        // palette.push_back(Color("#FF264A"));
        // palette.push_back(Color("#FF1942"));
        // palette.push_back(Color("#FF0D3B"));
        // palette.push_back(Color("#FF0033"));
        // palette.push_back(Color("#FF5C60"));
        // palette.push_back(Color("#FF525A"));
        // palette.push_back(Color("#FF4754"));
        // palette.push_back(Color("#FF3D4E"));
        // palette.push_back(Color("#FF3347"));
        // palette.push_back(Color("#FF2941"));
        // palette.push_back(Color("#FF1F3B"));
        // palette.push_back(Color("#FF1435"));
        // palette.push_back(Color("#FF0A2F"));
        // palette.push_back(Color("#FF0029"));
        // palette.push_back(Color("#FF4548"));
        // palette.push_back(Color("#FF3D43"));
        // palette.push_back(Color("#FF363F"));
        // palette.push_back(Color("#FF2E3A"));
        // palette.push_back(Color("#FF2636"));
        // palette.push_back(Color("#FF1F31"));
        // palette.push_back(Color("#FF172C"));
        // palette.push_back(Color("#FF0F28"));
        // palette.push_back(Color("#FF0823"));
        // palette.push_back(Color("#FF001F"));
        // palette.push_back(Color("#FF2E30"));
        // palette.push_back(Color("#FF292D"));
        // palette.push_back(Color("#FF242A"));
        // palette.push_back(Color("#FF1F27"));
        // palette.push_back(Color("#FF1924"));
        // palette.push_back(Color("#FF1421"));
        // palette.push_back(Color("#FF0F1E"));
        // palette.push_back(Color("#FF0A1B"));
        // palette.push_back(Color("#FF0517"));
        // palette.push_back(Color("#FF0014"));
        // palette.push_back(Color("#FFE3E3"));
        // palette.push_back(Color("#FFE0E1"));
        // palette.push_back(Color("#FFDEDF"));
        // palette.push_back(Color("#FFDBDD"));
        // palette.push_back(Color("#FFD9DB"));
        // palette.push_back(Color("#FFD6D9"));
        // palette.push_back(Color("#FFD4D7"));
        // palette.push_back(Color("#FFD1D5"));
        // palette.push_back(Color("#FFCFD3"));
        // palette.push_back(Color("#FFCCD1"));
        // palette.push_back(Color("#FFC7C8"));
        // palette.push_back(Color("#FFC2C4"));
        // palette.push_back(Color("#FFBDC0"));
        // palette.push_back(Color("#FFB8BC"));
        // palette.push_back(Color("#FFB3B8"));
        // palette.push_back(Color("#FFADB4"));
        // palette.push_back(Color("#FFA8AF"));
        // palette.push_back(Color("#FFA3AB"));
        // palette.push_back(Color("#FF9EA7"));
        // palette.push_back(Color("#FF99A3"));
        // palette.push_back(Color("#FFABAC"));
        // palette.push_back(Color("#FFA3A6"));
        // palette.push_back(Color("#FF9CA0"));
        // palette.push_back(Color("#FF949A"));
        // palette.push_back(Color("#FF8C94"));
        // palette.push_back(Color("#FF858E"));
        // palette.push_back(Color("#FF7D88"));
        // palette.push_back(Color("#FF7582"));
        // palette.push_back(Color("#FF6E7B"));
        // palette.push_back(Color("#FF6675"));
        // palette.push_back(Color("#FF8F91"));
        // palette.push_back(Color("#FF8589"));
        // palette.push_back(Color("#FF7A81"));
        // palette.push_back(Color("#FF7078"));
        // palette.push_back(Color("#FF6670"));
        // palette.push_back(Color("#FF5C68"));
        // palette.push_back(Color("#FF5260"));
        // palette.push_back(Color("#FF4758"));
        // palette.push_back(Color("#FF3D50"));
        // palette.push_back(Color("#FF3347"));
        // palette.push_back(Color("#FF7375"));
        // palette.push_back(Color("#FF666B"));
        // palette.push_back(Color("#FF5961"));
        // palette.push_back(Color("#FF4D57"));
        // palette.push_back(Color("#FF404C"));
        // palette.push_back(Color("#FF3342"));
        // palette.push_back(Color("#FF2638"));
        // palette.push_back(Color("#FF192E"));
        // palette.push_back(Color("#FF0D24"));
        // palette.push_back(Color("#FF0019"));
        // palette.push_back(Color("#FF5C5E"));
        // palette.push_back(Color("#FF5256"));
        // palette.push_back(Color("#FF474E"));
        // palette.push_back(Color("#FF3D45"));
        // palette.push_back(Color("#FF333D"));
        // palette.push_back(Color("#FF2935"));
        // palette.push_back(Color("#FF1F2D"));
        // palette.push_back(Color("#FF1425"));
        // palette.push_back(Color("#FF0A1D"));
        // palette.push_back(Color("#FF0014"));
        // palette.push_back(Color("#FF4546"));
        // palette.push_back(Color("#FF3D40"));
        // palette.push_back(Color("#FF363A"));
        // palette.push_back(Color("#FF2E34"));
        // palette.push_back(Color("#FF262E"));



        
        palette.push_back(Color("#FF1F28"));
        palette.push_back(Color("#FF1722"));
        palette.push_back(Color("#FF0F1C"));
        palette.push_back(Color("#FF0815"));
        palette.push_back(Color("#FF000F"));
        palette.push_back(Color("#FF2E2F"));
        palette.push_back(Color("#FF292B"));
        palette.push_back(Color("#FF2427"));
        palette.push_back(Color("#FF1F23"));
        palette.push_back(Color("#FF191F"));
        palette.push_back(Color("#FF141B"));
        palette.push_back(Color("#FF0F16"));
        palette.push_back(Color("#FF0A12"));
        palette.push_back(Color("#FF050E"));
        palette.push_back(Color("#FF000A"));
        palette.push_back(Color("#FFE3E3"));
        palette.push_back(Color("#FFE0E0"));
        palette.push_back(Color("#FFDEDE"));
        palette.push_back(Color("#FFDBDB"));
        palette.push_back(Color("#FFD9D9"));
        palette.push_back(Color("#FFD6D6"));
        palette.push_back(Color("#FFD4D4"));
        palette.push_back(Color("#FFD1D1"));
        palette.push_back(Color("#FFCFCF"));
        palette.push_back(Color("#FFCCCC"));
        palette.push_back(Color("#FFC7C7"));
        palette.push_back(Color("#FFC2C2"));
        palette.push_back(Color("#FFBDBD"));
        palette.push_back(Color("#FFB8B8"));
        palette.push_back(Color("#FFB3B3"));
        palette.push_back(Color("#FFADAD"));
        palette.push_back(Color("#FFA8A8"));
        palette.push_back(Color("#FFA3A3"));
        palette.push_back(Color("#FF9E9E"));
        palette.push_back(Color("#FF9999"));
        palette.push_back(Color("#FFABAB"));
        palette.push_back(Color("#FFA3A3"));
        palette.push_back(Color("#FF9C9C"));
        palette.push_back(Color("#FF9494"));
        palette.push_back(Color("#FF8C8C"));
        palette.push_back(Color("#FF8585"));
        palette.push_back(Color("#FF7D7D"));
        palette.push_back(Color("#FF7575"));
        palette.push_back(Color("#FF6E6E"));
        palette.push_back(Color("#FF6666"));
        palette.push_back(Color("#FF8F8F"));
        palette.push_back(Color("#FF8585"));
        palette.push_back(Color("#FF7A7A"));
        palette.push_back(Color("#FF7070"));
        palette.push_back(Color("#FF6666"));
        palette.push_back(Color("#FF5C5C"));
        palette.push_back(Color("#FF5252"));
        palette.push_back(Color("#FF4747"));
        palette.push_back(Color("#FF3D3D"));
        palette.push_back(Color("#FF3333"));
        palette.push_back(Color("#FF7373"));
        palette.push_back(Color("#FF6666"));
        palette.push_back(Color("#FF5959"));
        palette.push_back(Color("#FF4D4D"));
        palette.push_back(Color("#FF4040"));
        palette.push_back(Color("#FF3333"));
        palette.push_back(Color("#FF2626"));
        palette.push_back(Color("#FF1919"));
        palette.push_back(Color("#FF0D0D"));
        palette.push_back(Color("#FF0000"));
        palette.push_back(Color("#FF5C5C"));
        palette.push_back(Color("#FF5252"));
        palette.push_back(Color("#FF4747"));
        palette.push_back(Color("#FF3D3D"));
        palette.push_back(Color("#FF3333"));
        palette.push_back(Color("#FF2929"));
        palette.push_back(Color("#FF1F1F"));
        palette.push_back(Color("#FF1414"));
        palette.push_back(Color("#FF0A0A"));
        palette.push_back(Color("#FF0000"));
        palette.push_back(Color("#FF4545"));
        palette.push_back(Color("#FF3D3D"));
        palette.push_back(Color("#FF3636"));
        palette.push_back(Color("#FF2E2E"));
        palette.push_back(Color("#FF2626"));
        palette.push_back(Color("#FF1F1F"));
        palette.push_back(Color("#FF1717"));
        palette.push_back(Color("#FF0F0F"));
        palette.push_back(Color("#FF0808"));
        palette.push_back(Color("#FF0000"));
        palette.push_back(Color("#FF2E2E"));
        palette.push_back(Color("#FF2929"));
        palette.push_back(Color("#FF2424"));
        palette.push_back(Color("#FF1F1F"));
        palette.push_back(Color("#FF1919"));
        palette.push_back(Color("#FF1414"));
        palette.push_back(Color("#FF0F0F"));
        palette.push_back(Color("#FF0A0A"));
        palette.push_back(Color("#FF0505"));
        palette.push_back(Color("#FF0000"));
        palette.push_back(Color("#FFE3E3"));
        palette.push_back(Color("#FFE1E0"));
        palette.push_back(Color("#FFDFDE"));
        palette.push_back(Color("#FFDDDB"));
        palette.push_back(Color("#FFDBD9"));
        palette.push_back(Color("#FFD9D6"));
        palette.push_back(Color("#FFD7D4"));
        palette.push_back(Color("#FFD5D1"));
        palette.push_back(Color("#FFD3CF"));
        palette.push_back(Color("#FFD1CC"));
        palette.push_back(Color("#FFC8C7"));
        palette.push_back(Color("#FFC4C2"));
        palette.push_back(Color("#FFC0BD"));
        palette.push_back(Color("#FFBCB8"));
        palette.push_back(Color("#FFB8B3"));
        palette.push_back(Color("#FFB4AD"));
        palette.push_back(Color("#FFAFA8"));
        palette.push_back(Color("#FFABA3"));
        palette.push_back(Color("#FFA79E"));
        palette.push_back(Color("#FFA399"));
        palette.push_back(Color("#FFACAB"));
        palette.push_back(Color("#FFA6A3"));
        palette.push_back(Color("#FFA09C"));
        palette.push_back(Color("#FF9A94"));
        palette.push_back(Color("#FF948C"));
        palette.push_back(Color("#FF8E85"));
        palette.push_back(Color("#FF887D"));
        palette.push_back(Color("#FF8275"));
        palette.push_back(Color("#FF7B6E"));
        palette.push_back(Color("#FF7566"));
        palette.push_back(Color("#FF918F"));
        palette.push_back(Color("#FF8985"));
        palette.push_back(Color("#FF817A"));
        palette.push_back(Color("#FF7870"));
        palette.push_back(Color("#FF7066"));
        palette.push_back(Color("#FF685C"));
        palette.push_back(Color("#FF6052"));
        palette.push_back(Color("#FF5847"));
        palette.push_back(Color("#FF503D"));
        palette.push_back(Color("#FF4733"));
        palette.push_back(Color("#FF7573"));
        palette.push_back(Color("#FF6B66"));
        palette.push_back(Color("#FF6159"));
        palette.push_back(Color("#FF574D"));
        palette.push_back(Color("#FF4C40"));
        palette.push_back(Color("#FF4233"));
        palette.push_back(Color("#FF3826"));
        palette.push_back(Color("#FF2E19"));
        palette.push_back(Color("#FF240D"));
        palette.push_back(Color("#FF1900"));
        palette.push_back(Color("#FF5E5C"));
        palette.push_back(Color("#FF5652"));
        palette.push_back(Color("#FF4E47"));
        palette.push_back(Color("#FF453D"));
        palette.push_back(Color("#FF3D33"));
        palette.push_back(Color("#FF3529"));
        palette.push_back(Color("#FF2D1F"));
        palette.push_back(Color("#FF2514"));
        palette.push_back(Color("#FF1D0A"));
        palette.push_back(Color("#FF1400"));
        palette.push_back(Color("#FF4645"));
        palette.push_back(Color("#FF403D"));
        palette.push_back(Color("#FF3A36"));
        palette.push_back(Color("#FF342E"));
        palette.push_back(Color("#FF2E26"));
        palette.push_back(Color("#FF281F"));
        palette.push_back(Color("#FF2217"));
        palette.push_back(Color("#FF1C0F"));
        palette.push_back(Color("#FF1508"));
        palette.push_back(Color("#FF0F00"));
        palette.push_back(Color("#FF2F2E"));
        palette.push_back(Color("#FF2B29"));
        palette.push_back(Color("#FF2724"));
        palette.push_back(Color("#FF231F"));
        palette.push_back(Color("#FF1F19"));
        palette.push_back(Color("#FF1B14"));
        palette.push_back(Color("#FF160F"));
        palette.push_back(Color("#FF120A"));
        palette.push_back(Color("#FF0E05"));
        palette.push_back(Color("#FF0A00"));
        palette.push_back(Color("#FFE4E3"));
        palette.push_back(Color("#FFE2E0"));
        palette.push_back(Color("#FFE1DE"));
        palette.push_back(Color("#FFDFDB"));
        palette.push_back(Color("#FFDED9"));
        palette.push_back(Color("#FFDCD6"));
        palette.push_back(Color("#FFDBD4"));
        palette.push_back(Color("#FFD9D1"));
        palette.push_back(Color("#FFD8CF"));
        palette.push_back(Color("#FFD6CC"));
        palette.push_back(Color("#FFC9C7"));
        palette.push_back(Color("#FFC6C2"));
        palette.push_back(Color("#FFC3BD"));
        palette.push_back(Color("#FFC0B8"));
        palette.push_back(Color("#FFBDB3"));
        palette.push_back(Color("#FFBAAD"));
        palette.push_back(Color("#FFB7A8"));
        palette.push_back(Color("#FFB4A3"));
        palette.push_back(Color("#FFB09E"));
        palette.push_back(Color("#FFAD99"));
        palette.push_back(Color("#FFAEAB"));
        palette.push_back(Color("#FFA9A3"));
        palette.push_back(Color("#FFA59C"));
        palette.push_back(Color("#FFA094"));
        palette.push_back(Color("#FF9C8C"));
        palette.push_back(Color("#FF9785"));
        palette.push_back(Color("#FF927D"));
        palette.push_back(Color("#FF8E75"));
        palette.push_back(Color("#FF896E"));
        palette.push_back(Color("#FF8566"));
        palette.push_back(Color("#FF938F"));
        palette.push_back(Color("#FF8D85"));
        palette.push_back(Color("#FF877A"));
        palette.push_back(Color("#FF8170"));
        palette.push_back(Color("#FF7A66"));
        palette.push_back(Color("#FF745C"));
        palette.push_back(Color("#FF6E52"));
        palette.push_back(Color("#FF6847"));
        palette.push_back(Color("#FF623D"));
        palette.push_back(Color("#FF5C33"));
        palette.push_back(Color("#FF525E"));
        palette.push_back(Color("#FF7D88"));
        palette.push_back(Color("#FF7582"));
        palette.push_back(Color("#FF6E7B"));
        palette.push_back(Color("#FF6675"));
        palette.push_back(Color("#FF8F91"));
        palette.push_back(Color("#FF8589"));
        palette.push_back(Color("#FF7A81"));
        palette.push_back(Color("#FF7078"));
        palette.push_back(Color("#FF6670"));
        palette.push_back(Color("#FF5C68"));
        palette.push_back(Color("#FF5260"));
        palette.push_back(Color("#FF4758"));
        palette.push_back(Color("#FF3D50"));
        palette.push_back(Color("#FF3347"));
        palette.push_back(Color("#FF7375"));
        palette.push_back(Color("#FF666B"));
        palette.push_back(Color("#FF5961"));
        palette.push_back(Color("#FF4D57"));
        palette.push_back(Color("#FF404C"));
        palette.push_back(Color("#FF3342"));
        palette.push_back(Color("#FF2638"));
        palette.push_back(Color("#FF192E"));
        palette.push_back(Color("#FF0D24"));
        palette.push_back(Color("#FF0019"));
        palette.push_back(Color("#FF5C5E"));
        palette.push_back(Color("#FF5256"));
        palette.push_back(Color("#FF474E"));
        palette.push_back(Color("#FF3D45"));
        palette.push_back(Color("#FF333D"));
        palette.push_back(Color("#FF2935"));
        palette.push_back(Color("#FF1F2D"));
        palette.push_back(Color("#FF1425"));
        palette.push_back(Color("#FF0A1D"));
        palette.push_back(Color("#FF0014"));
        palette.push_back(Color("#FF4546"));
        palette.push_back(Color("#FF3D40"));
        palette.push_back(Color("#FF363A"));
        palette.push_back(Color("#FF2E34"));
        palette.push_back(Color("#FF262E"));
    }
    ~Palette() { }
    int Count() { return palette.size(); }
    Color GetColor(int index)
    {
        list<Color>::iterator it = palette.begin();
        advance(it, index);
        return *it;
    }
};